### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ibuilddumbrobots** [sudurraaa/queen#2]
Traceback (most recent call last):
  File "/home/azrail/Junk/queen/queen.py", line 119, in <module>
    main(sys.argv[1])
  File "/home/azrail/Junk/queen/queen.py", line 91, in main
    hack_request = requests.post(instagram_url_login, data=payload, headers=login_header, proxies=proxy)
  File "/home/azrail/.local/lib/python3.9/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/azrail/.local/lib/python3.9/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/azrail/.local/lib/python3.9/site-packages/requests/sessions.py", line 492, in request
    settings = self.merge_environment_settings(
  File "/home/azrail/.local/lib/python3.9/site-packages/requests/sessions.py", line 665, in merge_environment_settings
    no_proxy = proxies.get('no_proxy') if proxies is not None else None
AttributeError: 'str' object has no attribute 'get'

**Comment by gorxyz** [comment]
Hi,looks like you havent tor enabled
Today i added argparser that's would be much easier
try 
```bash
python3 queen.py --tor disable
````
or just try queen.py -h
