### ISSUE TITLE
csrf token issue

### ISSUE THREAD

**Issue by jhoanmartinez** [sudurraaa/queen#7]
Hello fellas, when I ran the code, shows up this issue, its about csrf token

Try the 2 options: python3 queen.py --tor disbale and python3 queen.py --tor enable, shows the same issue

Traceback (most recent call last):
  File "/home/queen/queen.py", line 31, in <module>
    csrf = cookie_request.cookies['csrftoken']
  File "/home/queen/env3.10/lib/python3.10/site-packages/requests/cookies.py", line 334, in __getitem__
    return self._find_no_duplicates(name)
  File "/home/queen/env3.10/lib/python3.10/site-packages/requests/cookies.py", line 413, in _find_no_duplicates
    raise KeyError(f"name={name!r}, domain={domain!r}, path={path!r}")
KeyError: "name='csrftoken', domain=None, path=None"

Maybe request library change or instagram not returning csrftoken

Try to print the cookies:

cookie_request = requests.get(instagram_url)
print(cookie_request.cookies.get_dict())   =====> output ===> {}

Am I missing something guys?

**Comment by TheRiddler2** [comment]
Yep, I'm experiencing the same problem.
![Screenshot 2023-06-02 145554](https://github.com/gorxyz/queen/assets/97083513/25dfc8b8-1d5f-4a53-8e52-f22f03a0e6b1)
